### PR TITLE
Setup Mock Server

### PR DESCRIPTION
**Pull request by aremu-smog**
## 1. Objective
- For days when we do not need to rely on data from WordPress and get the job done

**Philosophy:**
So I setup a mini source plugin which basically pulls dummy data from `.js` files which basically exports objects. The code can be found in `plugins/gatsby-mock-graphql`, the core logic is in `gatsby-node.js` in the directory

In order to mock images (images coming from Wordpress) as well, I created a new image component called `ImageWithMock` which is basically a wrapper around `GatsbyImage` and returns a static image with a dummy image in the codebase whenever a mock image is being returned. 

**So why is this PR build failing**

Because we are pointing directly to production, and we don't want to enable mocks in production. Time to setup a staging environment @Joponpin2000 can you help out with this? We could sync up on it. But I think the code should be merged first, customers wouldn't notice a difference.

## 3. Quality assurance

PS: You may need to test this locally for now

Add `GATSBY_ENABLE_MOCKS` to your environment variable

- Run `gatsby develop`, all pages should load and work normally with dummy/mock data

## 4. Operations impact

Add `GATSBY_ENABLE_MOCKS` to environment variable (be careful to do this only for previews) or staging environment.

## 5. Business impact

Empower engineers to move fater

## 6. Priority of Change

Normal

### CODE REVIEW

**Comment by the-jossie** [comment]
@aremu-smog when can we have the sync?

**Comment by aremu-smog** [comment]
How does 6PM today sound @Joponpin2000 ?

**Comment by Demoivre02** [comment]
Please a visual presentation would be appreciated, i don't really get what is going on
can we make the meeting 8pm?

**Comment by aremu-smog** [comment]
@Demoivre02 did you read through the PR description? And try to follow the steps in the Quality Assurance section?

For the meeting, it's basically to setup the staging not a deep dive into code and it's kind of optional. @Joponpin2000 what time works for you?

**Comment by the-jossie** [comment]
@aremu-smog just seeing this. 6pm/7pm works for me

**Comment by aremu-smog** [comment]
@Joponpin2000 @Demoivre02 , here is the link: Setup Staging for OFT
Tuesday, 18 July · 18:00 – 19:00
Time zone: Africa/Lagos
Google Meet joining info
Video call link: https://meet.google.com/gza-queq-ymp

**Comment by Demoivre02** [comment]
i'm sorry i wasn't able to attend, i had a run by that time, that was why i suggested 8pm, i'll ask Joseph for the updates

**Comment by aremu-smog** [comment]
Oh... Definitely not a problem.

**Comment by the-jossie** [comment]
@aremu-smog do you still want to leave this as Draft?

**Comment by aremu-smog** [comment]
My bad @Joponpin2000 ,

I should probably close this and raise the MR from the staging branch since that contains the latest working updates. Or what do you think?

**Comment by the-jossie** [comment]
Yes, that'd be better.

**Comment by the-jossie** [comment]
@aremu-smog

**Comment by aremu-smog** [comment]
Apologies for the delay.

**Pull request closed without merging**
