### PR TITLE
Da page curvy lines

### PR DESCRIPTION
**Pull request by Demoivre02**
## 1. Objective
Explain `WHY` this PR is required e.g What feature it adds, what problem it solves, ...
Add the beautiful curvy lines to the edges of the landing page, resource page and the about page.

Related Link(s)
- [TaskID](#)
- #

## 2. Description of change
-import left svg and right svg from the assets folder
-Modified the landing page header section and the  landing page and resource page header sections
-Added the svgs

## 3. Quality assurance

Check the landing page, resource page and the about page.

## 4. Operations impact
N/A

## 5. Business impact

N/A

## 6. Priority of Change
Normal

### CODE REVIEW

**Comment by aremu-smog** [comment]
@Demoivre02 kindly update the PR description

**Comment by Demoivre02** [comment]
> @Demoivre02 kindly update the PR description

@aremu-smog done, kindly check

**Comment by aremu-smog** [comment]
> > @Demoivre02 kindly update the PR description
> 
> @aremu-smog done, kindly check

So @Demoivre02 , the objective is not correct and the related links are also leading to a dead link.

It's also alright to add `N/A` to any section that you don't know what to put.

Also, kindly request a review from @Joponpin2000 and I

**Comment by aremu-smog** [comment]
So quick one regarding the implementation. 
The SVG looks kinda big. 
Also, it should be touching the edge of the screen not inside the container.

**Comment by aremu-smog** [comment]
Hi @Demoivre02 , 

I am checking in if the fixes have being made.
Also kindly add @Joponpin2000 and I as reviewers so we are notified in any changes is made on the 
PR:
image

**Comment by aremu-smog** [comment]
Hi @Demoivre02 , the fixes are still not done. 
Would be jumping on this and pushing.

**Comment by aremu-smog** [comment]
Hi @Demoivre02 ,

I see you tried to push some fixes along the way while working on this ticket.

While it's a 'great' idea, It's better to 'log' things first and pick them up.

That way there is more visibility into the work being done and the person reviewing the code is not meant with surprises.

I think it's always a great idea to think about the other person while making decisions. 

Apologies if you don't find some the things you have worked on when this goes out.

**Comment by Demoivre02** [comment]
> Hi @Demoivre02 ,
> 
> I see you tried to push some fixes along the way while working on this ticket.
> 
> While it's a 'great' idea, It's better to 'log' things first and pick them up.
> 
> That way there is more visibility into the work being done and the person reviewing the code is not meant with surprises.
> 
> I think it's always a great idea to think about the other person while making decisions.
> 
> Apologies if you don't find some the things you have worked on when this goes out.

understood boss
thanks

**Pull request merged**
