### PR TITLE
JI Update Team Members section on about page

### PR DESCRIPTION
**Pull request by the-jossie**
## 1. Objective
This MR updates the team members section on about page

- [Trello](https://trello.com/c/XzqALF0E/1-update-team-members-section-on-about-page)
- [Figma](https://www.figma.com/file/k1f5xtKXLN9ztBftxmn5eI/Other-faces-of-Tech-hand-off?type=design&node-id=945-455&mode=design&t=SMzQEPvDk9DxJijU-0)

## 2. Quality assurance
- Assert that when you go to `/about-us` page, you see the new design

## 3. Operations impact
- make sure to run `npm install`

## 4. Priority of Change
- Normal

### CODE REVIEW

**Review by aremu-smog — DISMISSED** [review]
Looks good, can we put `Akinwoye Dolapo` under **Product & Design**

**Comment by the-jossie** [comment]
@aremu-smog @Demoivre02 Please help approve. I just rebased to fix the merge conflict

**Comment by aremu-smog** [comment]
Hi @Joponpin2000 , I left a comment yesterday. Akinwoye Dolapo should be under Product and Design

**Comment by the-jossie** [comment]
@aremu-smog yes, I fixed that already

**Comment by Joponpin2000** [comment]
Screenshot 2023-07-11 at 4 29 27 PM

**Pull request merged**
